export { MoveAction, MoveToAction, MoveSystem };

import { Action } from './action.js';
import { EvtSystem } from './event.js';
import { Vect } from './vect.js';
import { System } from './system.js';
import { Stats } from './stats.js';
import { Mathf } from './math.js';
import { Fmt } from './fmt.js';

class MoveAction extends Action {

    static {
        this.schema('speed', { dflt: 0 });
        this.schema('targetSpeed', { parser: (o,x) => x.hasOwnProperty('targetSpeed') ? x.targetSpeed : o.speed });
        this.schema('accel', { dflt: 0 });
        this.schema('heading', { dflt: 0 });
        this.schema('overx', { dflt: 0, eventable: false });
        this.schema('overy', { dflt: 0, eventable: false });
        // -- autogenerated dx/dy, regenerated upon heading changes
        this.schema('dx', { eventable: false, generator: (o, x) => Math.cos(o.heading) });
        this.schema('dy', { eventable: false, generator: (o, x) => Math.sin(o.heading) });
    }

    doperform(ctx) {}

    toString() {
        return Fmt.toString(this.constructor.name, this.speed, this.heading);
    }

}

class MoveToAction extends MoveAction {
    static {
        this.schema('target', { });
        this.schema('snap', { dflt: false });
        this.schema('range', { parser: (o,x) => x.hasOwnProperty('range') ? x.range : o.constructor.dfltRange });
        this.schema('chained', { dflt: false });
        // facing?
    }

    static dfltRange = 5;

    toString() {
        return Fmt.toString(this.constructor.name, this.speed, this.target);
    }
}

class MoveSystem extends System {
    static dfltMatchFcn = ((gzo) => (gzo instanceof MoveAction && gzo.actor) );

    static {
        this.schema('actorLocator', { eventable: false, dflt: (actor) => (actor) ? new Vect({x:actor.xform.x, y:actor.xform.y}) : Vect.zero });
        this.schema('targetLocator', { eventable: false, dflt: (target) => target });
        this.schema('actorMover', { eventable: false, dflt: (actor, loc) => { if (actor && loc) { actor.xform.x = loc.x; actor.xform.y = loc.y }}} );
        this.schema('minDelta', { eventable: false, dflt: .001 });
        this.schema('minSpeed', { eventable: false, dflt: .001 });
    }

    static dfltIterateTTL = 0;

    cpost(spec) {
        super.cpost(spec);
        // bind event handlers 
        this.onMoveStarted = this.onMoveStarted.bind(this);
        EvtSystem.listen(this.gctx, this, 'action.started', this.onMoveStarted, { filter: (evt) => (evt.action instanceof MoveAction) });
    }

    onMoveStarted(evt) {
        let action = evt.action;
        if (!action) return;
        if (!this.store.has(action.gid)) {
            this.store.set(action.gid, action);
            EvtSystem.listen(action, this, 'action.done', (evt) => {
                this.store.delete(action.gid);
            });
        }
    }

    iterate(evt, e) {
        Stats.count('move.iterate');
        let actorLoc = this.actorLocator(e.actor);
        let targetLoc;
        // adjust speed based on acceleration
        if (e.accel) {
            // handle acceleration
            if (e.speed < e.targetSpeed) {
                e.speed = Math.min(e.speed + e.accel * evt.deltaTime, e.targetSpeed);
            // handle deceleration
            } else if (e.speed > e.targetSpeed) {
                e.speed = Math.max(e.speed - e.accel * evt.deltaTime, 0);
                if (e.speed < this.minSpeed) e.speed = 0;
            }
        } else {
            if (e.hasOwnProperty('targetSpeed')) e.speed = e.targetSpeed;
        }
        // calculate heading change to target
        // -- if drastic change of heading, reset overx/overy
        if (e.target) {
            targetLoc = this.targetLocator(e.target);
            let newHeading = Mathf.angle(actorLoc.x, actorLoc.y, targetLoc.x, targetLoc.y, true);
            if (newHeading) {
                if (Mathf.angleBetween(newHeading, e.heading) > Math.PI*.25) {
                    e.overx = 0;
                    e.overy = 0;
                }
            }
            e.heading = newHeading;
        }
        // move actor based on current speed and heading
        let espeed = e.speed * evt.deltaTime;
        // determine desired position based on speed and heading
        let dx = espeed * e.dx + e.overx;
        let dy = espeed * e.dy + e.overy;
        //console.log(`iterate speed: ${e.speed} heading: ${e.heading} e.d: ${e.dx},${e.dy} over: ${e.overx},${e.overy} d: ${dx},${dy}`);
        // handle rollover of partial pixels
        if (Math.abs(dx)>this.minDelta) {
            if (Math.abs(dx) >= 1) {
                let rx = (dx > 0) ? Math.floor(dx) : Math.floor(dx)+1;
                actorLoc.x += rx;
                e.overx = dx-rx;
            } else {
                e.overx = dx;
            }
        }
        if (Math.abs(dy)>this.minDelta) {
            if (Math.abs(dy) >= 1) {
                let ry = (dy > 0) ? Math.floor(dy) : Math.floor(dy)+1;
                actorLoc.y += ry;
                e.overy = dy-ry;
            } else {
                e.overy = dy;
            }
        }
        this.actorMover(e.actor, actorLoc);
        // if action has target ... handle movement tracking to target
        let targetReached = false;
        if (e.target) {
            let distance = Mathf.distance(targetLoc.x, targetLoc.y, actorLoc.x, actorLoc.y);
            // as we approach target, calculate distance required to slow down, start slowing down when we reach that distance
            if (e.accel) {
                let decelDistance = (e.speed * e.speed) / (2 * e.accel);
                if (distance < decelDistance) e.targetSpeed = 0;
            }
            // if we are within range of target...
            if (distance <= e.range) {
                targetReached = true;
                if (this.dbg) console.log(`${e.actor} arrived in range of target: ${targetLoc}`);
                // if movement is chained, target speed is maintained and action is done... 
                if (!e.chained) {
                    e.targetSpeed = 0;
                    e.speed = 0;
                }
                // snap to target if set
                if (e.snap) this.actorMover(e.actor, targetLoc);
            }
        }
        // complete action if target is reached or speed is zero'd
        if (targetReached || (e.speed === 0 && e.targetSpeed === 0)) {
            e.finish(e.ok);
        }
    }

}
